#!/usr/bin/env python3
"""Milnor's mu-bar invariants by truncated Magnus expansion of the longitudes.

Needed because the two survivors of the 4-component Eisermann census,
`L14n62566` and `L14n63195`, are Brunnian: every proper sublink is an unlink,
so every Milnor invariant of length <= 3 vanishes automatically and the first
one that can obstruct sliceness is `mu-bar(1234)`.  Brunnian-ness is also what
makes it an honest integer -- the usual indeterminacy is generated by the
shorter invariants, and here they are all zero.

`nabla_L = 0` does NOT settle it.  The identity `[z^4] nabla = mu-bar(123)^2`
holds for 3-component links with vanishing linking numbers (Cochran); no
analogue at length 4 is asserted here, so the invariant is computed directly.

Method.  Wirtinger presentation from the diagram: position 0 of a spherogram
crossing is the incoming under-strand, position 2 the outgoing one, and the
incoming over-strand is at position 1 when the sign is -1 and position 3 when
it is +1.  Each arc gets a meridian; at a crossing the outgoing under-meridian
is the incoming one conjugated by the over-meridian.  Expanding meridians as
truncated power series in non-commuting X_0..X_{n-1} and propagating those
relations gives the Magnus expansion of every meridian, hence of the 0-framed
longitudes, and

    mu-bar(i_1 ... i_k j) = coefficient of X_{i_1}...X_{i_k} in longitude_j.

Conventions are pinned by the controls, and pinning them was not optional: of
the four sign choices (conjugation direction x longitude exponent), two give
expansions that satisfy the shuffle relations but VIOLATE the cyclic symmetry
`mu(i_1...i_k) = mu(i_2...i_k i_1)`, and on those the Whitehead link returns
`mu(1122) = 0` instead of the correct +-1.  The two admissible choices differ
only by an overall mirror; the one adopted here gives the positive Hopf link
`lk = +1`.  Controls must return: Hopf `mu(12) = 1`, Whitehead
`mu(1122) = 1`, Borromean `mu(123) = 1`, unlinks 0, and Whitehead cyclic
symmetry `mu(1122) = mu(1221)`.

Usage:
    milnor_invariants.py --controls
    milnor_invariants.py <links.json> <out.json>
"""
import json, os, sys, itertools, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import snappy


class Trunc:
    """Non-commutative power series over Z, truncated at total degree D."""
    __slots__ = ('d', 'D')

    def __init__(self, d=None, D=4):
        self.D = D
        self.d = dict(d) if d else {}
        self.d = {w: c for w, c in self.d.items() if c}

    @classmethod
    def one(cls, D):
        return cls({(): 1}, D)

    @classmethod
    def gen(cls, i, D):
        return cls({(): 1, (i,): 1}, D)

    def __mul__(self, other):
        out = {}
        for w1, c1 in self.d.items():
            for w2, c2 in other.d.items():
                if len(w1) + len(w2) > self.D:
                    continue
                w = w1 + w2
                out[w] = out.get(w, 0) + c1 * c2
        return Trunc(out, self.D)

    def inverse(self):
        """Inverse of 1 + u with u of positive degree: 1 - u + u^2 - ..."""
        const = self.d.get((), 0)
        assert const == 1, 'only units with constant term 1 are inverted'
        u = Trunc({w: c for w, c in self.d.items() if w}, self.D)
        out = Trunc.one(self.D)
        term = Trunc.one(self.D)
        for k in range(1, self.D + 1):
            term = term * u
            if not term.d:
                break
            out = out + Trunc({w: (-1) ** k * c for w, c in term.d.items()}, self.D)
        return out

    def __add__(self, other):
        out = dict(self.d)
        for w, c in other.d.items():
            out[w] = out.get(w, 0) + c
        return Trunc(out, self.D)

    def power(self, e):
        if e == 0:
            return Trunc.one(self.D)
        base = self if e > 0 else self.inverse()
        out = Trunc.one(self.D)
        for _ in range(abs(e)):
            out = out * base
        return out

    def coeff(self, word):
        return self.d.get(tuple(word), 0)


def _arc_ids(L):
    """Map each (crossing, position) to an arc id, merging over-strands."""
    parent = {}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for c in L.crossings:
        for p in range(4):
            parent.setdefault((c, p), (c, p))
    # an arc runs along the diagram, broken only at under-crossings
    for c in L.crossings:
        over_in = 1 if c.sign == -1 else 3
        over_out = 3 if c.sign == -1 else 1
        union((c, over_in), (c, over_out))          # over-strand is one arc
        for p in range(4):
            c2, p2 = c.adjacent[p]
            union((c, p), (c2, p2))                 # glue along edges
    ids, out = {}, {}
    for key in parent:
        r = find(key)
        if r not in ids:
            ids[r] = len(ids)
        out[key] = ids[r]
    return out


def magnus_longitudes(L, D=4):
    """(longitudes, n) with longitudes[j] the Magnus expansion of lambda_j."""
    L = L.copy()
    n = len(L.link_components)
    arc = _arc_ids(L)
    comp_of_arc = {}
    for j, comp in enumerate(L.link_components):
        for ce in comp:
            comp_of_arc.setdefault(arc[(ce.crossing, ce.strand_index)], j)
            opp = (ce.strand_index + 2) % 4
            comp_of_arc.setdefault(arc[(ce.crossing, opp)], j)
    # seed one arc per component, then propagate the Wirtinger relations
    exp = {}
    for j, comp in enumerate(L.link_components):
        ce = comp[0]
        exp[arc[(ce.crossing, ce.strand_index)]] = Trunc.gen(j, D)
    for _ in range(4 * len(L.crossings) + 4):
        changed = False
        for c in L.crossings:
            over_in = 1 if c.sign == -1 else 3
            a_in, a_out = arc[(c, 0)], arc[(c, 2)]
            a_over = arc[(c, over_in)]
            if a_over not in exp:
                continue
            o = exp[a_over]
            if a_in in exp and a_out not in exp:
                exp[a_out] = o.power(c.sign) * exp[a_in] * o.power(-c.sign)
                changed = True
            elif a_out in exp and a_in not in exp:
                exp[a_in] = o.power(-c.sign) * exp[a_out] * o.power(c.sign)
                changed = True
        if not changed:
            break
    longs = []
    for j, comp in enumerate(L.link_components):
        lam = Trunc.one(D)
        writhe = 0
        for ce in comp:
            if ce.strand_index != 0:          # only under-passes contribute
                continue
            c = ce.crossing
            over_in = 1 if c.sign == -1 else 3
            a_over = arc[(c, over_in)]
            if a_over not in exp:
                raise RuntimeError('meridian propagation incomplete')
            lam = lam * exp[a_over].power(-c.sign)
            if comp_of_arc.get(a_over) == j:
                writhe += c.sign
        base = exp[arc[(comp[0].crossing, comp[0].strand_index)]]
        lam = lam * base.power(writhe)
        longs.append(lam)
    return longs, n


def mu_bar(L, indices):
    """mu-bar(i_1 ... i_k j) for indices = (i_1,...,i_k,j), 0-based."""
    longs, n = magnus_longitudes(L, D=max(4, len(indices)))
    *pre, j = indices
    return longs[j].coeff(pre)


def _controls():
    cases = [
        ('unlink O^2', snappy.Link(braid_closure=[1, -1]), (0, 1), 0),
        ('unlink O^3', snappy.Link(braid_closure=[1, -1, 2, -2]), (0, 1, 2), 0),
        ('Hopf L2a1', snappy.Link('L2a1'), (0, 1), 1),
        ('Whitehead L5a1', snappy.Link('L5a1'), (0, 0, 1, 1), 1),
        ('Borromean L6a4', snappy.Link('L6a4'), (0, 1, 2), 1),
        ('Whitehead cyclic', snappy.Link('L5a1'), (0, 1, 1, 0), 1),
    ]
    rows, ok = [], True
    for name, L, idx, want_nonzero in cases:
        try:
            v = mu_bar(L, idx)
            err = None
        except Exception as e:
            v, err = None, f'{type(e).__name__}: {e}'
        good = (err is None) and ((abs(v) > 0) == bool(want_nonzero))
        ok = ok and good
        rows.append({'case': name, 'indices': list(idx), 'mu_bar': v,
                     'expected_nonzero': bool(want_nonzero),
                     'as_expected': good, 'error': err})
        print(('ok  ' if good else 'MISMATCH') +
              f' {name:16s} mu{idx} = {v}  (expected '
              f'{"nonzero" if want_nonzero else "0"})', flush=True)
    out = 'results/session_2026-09-15b/milnor_controls.json'
    os.makedirs(os.path.dirname(out), exist_ok=True)
    json.dump({'date': datetime.datetime.utcnow().isoformat() + 'Z',
               'what': 'controls pinning the Magnus/Wirtinger conventions',
               'rows': rows, 'all_as_expected': ok}, open(out, 'w'), indent=1)
    print('wrote', out)
    return ok


if __name__ == '__main__':
    if sys.argv[1] == '--controls':
        sys.exit(0 if _controls() else 1)
    src, out_path = sys.argv[1], sys.argv[2]
    d = json.load(open(src))
    by = {r['name']: r for r in d['rows'] if 'pd_code' in r}
    rec = {'date': datetime.datetime.utcnow().isoformat() + 'Z', 'source': src,
           'rows': []}
    for name in d.get('survivors', []):
        row = by.get(name)
        if row is None:
            continue
        L = snappy.Link([tuple(c) for c in row['pd_code']])
        n = len(L.link_components)
        vals = {}
        for idx in itertools.permutations(range(n)):
            if idx[-1] != n - 1:
                continue
            try:
                vals[str(idx)] = mu_bar(L, idx)
            except Exception as e:
                vals[str(idx)] = f'{type(e).__name__}: {e}'
        nonzero = {k: v for k, v in vals.items() if isinstance(v, int) and v}
        rec['rows'].append({'name': name, 'components': n,
                            'mu_bar_length_n': vals,
                            'slice_ruled_out': bool(nonzero)})
        print(f'{name:12s} mu-bar of length {n}: {vals}  '
              + ('RULED OUT of slice' if nonzero else '*** STILL LIVE ***'),
              flush=True)
    json.dump(rec, open(out_path, 'w'), indent=1)
    print('wrote', out_path)
