#!/usr/bin/env python3
"""Why every classical concordance invariant of the Abe-Tagami family agrees.

LEMMA.  Let K and K' be knots and suppose there is an orientation preserving
homeomorphism M(K) -> M(K') of the zero-framed surgeries carrying the meridian
class to the meridian class.  Then the Seifert matrices of K and K' are
S-equivalent, so [K] = [K'] in the algebraic concordance group, and K # (-K')
is algebraically slice.

PROOF.  (i) The Blanchfield pairing of K is defined intrinsically on M(K):
Borodzik-Friedl, "The unknotting number and classical invariants I"
(arXiv:1203.3225), Section "The Blanchfield pairing and intersection pairings
on 4-manifolds", write M := M(K) for the zero framed surgery and state "It is
well-known that the natural map H_1(X(K);L) -> H_1(M;L) is an isomorphism, and
it follows immediately that the Blanchfield pairing on X(K) is isometric to
the pairing (\\ref{equ:blanonM}) on M."  The meridian-preserving hypothesis is
what identifies the two L = Z[t,t^{-1}] structures.
(ii) The isometry type of the Blanchfield pairing determines the S-equivalence
class of the Seifert matrix: Trotter, "On S-equivalence of Seifert matrices",
Invent. Math. 20 (1973), 173-207; quoted in the same section of Borodzik-Friedl
as "Note that the isometry type of the Blanchfield pairing in fact determines
the S-equivalence class of the Seifert matrix, see [Tro73] and [Ran03]. In that
sense the Blanchfield pairing is a 'complete' classical invariant, i.e. it
determines all other classical invariants."
(iii) S-equivalent Seifert matrices have the same Witt class in the algebraic
concordance group (S-equivalence is generated by enlargement/congruence, both
of which preserve the Witt class).  QED

APPLICATION.  The n-fold annulus twist is supported in a neighbourhood of the
annulus, which is disjoint from K, and Abe-Jong-Omae-Takeuchi's theorem says it
does not change the zero surgery.  The resulting homeomorphism is the identity
near K, hence preserves the meridian.  So the hypothesis holds for every pair
K_n, K_m in the Abe-Tagami family and

    D_{n,m} = K_n # (-K_m) is algebraically slice, for a structural reason.

CONSEQUENCE, stated as an exclusion.  No invariant that factors through the
S-equivalence class of the Seifert matrix can ever obstruct sliceness of any
D_{n,m}.  That includes: the Alexander polynomial and Fox-Milnor, the Alexander
module and Blanchfield pairing, all Levine-Tristram signatures and nullities,
Milnor signatures, the Arf invariant, and the Levine algebraic concordance
class.  Computing any of them on this family is an audit, not a test.  This
does NOT cover Casson-Gordon invariants, twisted Alexander/metabelian
obstructions, d-invariants of branched covers, or any gauge-theoretic or Floer
invariant: none of those factors through S-equivalence.

This script checks the numerical predictions of the lemma.

Usage: python3 scripts/zero_surgery_algebraic_concordance.py <out.json>
"""
import json, math, cmath, os, sys
import snappy

SAMPLES = 24


def seifert(pd):
    return [[int(x) for x in r]
            for r in snappy.Link([tuple(c) for c in pd]).seifert_matrix()]


def signature(V, w):
    n = len(V)
    M = [[(1 - w) * V[i][j] + (1 - w.conjugate()) * V[j][i] for j in range(n)]
         for i in range(n)]
    used = [False] * n
    pos = neg = 0
    for _ in range(n):
        p, best = None, 0.0
        for i in range(n):
            if not used[i] and abs(M[i][i].real) > best:
                best, p = abs(M[i][i].real), i
        if p is None or best < 1e-9:
            rem = [i for i in range(n) if not used[i]]
            if all(abs(M[i][j]) < 1e-7 for i in rem for j in rem):
                break
            p = rem[0]
            q = [i for i in rem if abs(M[p][i]) > 1e-9]
            if not q:
                used[p] = True
                continue
            q = q[0]
            for j in range(n):
                M[p][j] += M[q][j]
            for i in range(n):
                M[i][p] += M[i][q]
        used[p] = True
        if M[p][p].real > 0:
            pos += 1
        else:
            neg += 1
        for i in range(n):
            if used[i] or abs(M[i][p]) < 1e-14:
                continue
            f = M[i][p] / M[p][p]
            for j in range(n):
                M[i][j] -= f * M[p][j]
    return pos - neg


def int_det(M):
    """Exact integer determinant, fraction-free Bareiss."""
    A = [row[:] for row in M]
    n = len(A)
    sign = 1
    prev = 1
    for k in range(n - 1):
        if A[k][k] == 0:
            piv = next((i for i in range(k + 1, n) if A[i][k] != 0), None)
            if piv is None:
                return 0
            A[k], A[piv] = A[piv], A[k]
            sign = -sign
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                A[i][j] = (A[i][j] * A[k][k] - A[i][k] * A[k][j]) // prev
        prev = A[k][k]
    return sign * A[n - 1][n - 1]


def alexander(V):
    """Alexander polynomial of K from det(tV - V^T), by exact integer Lagrange
    interpolation; returns the primitive polynomial with nonzero constant term
    and positive leading coefficient, coefficients low degree first."""
    from fractions import Fraction

    def pmul(a, b):
        out = [Fraction(0)] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    out[i + j] += x * y
        return out

    n = len(V)
    deg = n
    xs = list(range(1, deg + 2))
    ys = [int_det([[x * V[i][j] - V[j][i] for j in range(n)] for i in range(n)])
          for x in xs]
    coeffs = [Fraction(0)] * (deg + 1)
    for i, xi in enumerate(xs):
        num = [Fraction(1)]
        den = Fraction(1)
        for j, xj in enumerate(xs):
            if i == j:
                continue
            num = pmul(num, [Fraction(-xj), Fraction(1)])
            den *= (xi - xj)
        scale = Fraction(ys[i], 1) / den
        for k, v in enumerate(num):
            coeffs[k] += v * scale
    assert all(v.denominator == 1 for v in coeffs), coeffs
    c = [int(v) for v in coeffs]
    while c and c[-1] == 0:
        c.pop()
    while c and c[0] == 0:
        c.pop(0)
    if c and c[-1] < 0:
        c = [-x for x in c]
    return c


def main(out_path):
    if os.path.exists(out_path):
        sys.exit('refusing to overwrite %s' % out_path)
    import sympy
    t = sympy.symbols('t')
    targets = (('K_0 (= 6_3)', 'AbeTagami_K_0_K_-1__6_3'),
               ('K_1', 'AbeTagami_K_1'),
               ('K_2', 'AbeTagami_K_2'))
    V = {}
    for lab, f in targets:
        pd = json.load(open('data/knots/%s.json' % f))['pd_code_snappy_0indexed']
        V[lab] = seifert(pd)
    for nm in ('3_1', '4_1'):
        V['control %s' % nm] = seifert(snappy.Link(nm).PD_code())

    out = {'snappy': snappy.version(), 'sympy': sympy.__version__,
           'levine_tristram': {}, 'alexander': {}, 'seifert_size': {}}
    omegas = [k / float(2 * SAMPLES) for k in range(1, SAMPLES + 1)]
    out['omega_exponents'] = omegas
    for lab in V:
        out['seifert_size'][lab] = len(V[lab])
        out['levine_tristram'][lab] = [
            signature(V[lab], cmath.exp(2j * math.pi * s)) for s in omegas]
    for lab in list(V):
        if len(V[lab]) <= 40:
            out['alexander'][lab] = alexander(V[lab])
    delta = out['alexander'].get('K_0 (= 6_3)')
    out['delta_K0'] = delta
    out['delta_K1'] = out['alexander'].get('K_1')
    out['delta_irreducible_over_Q'] = bool(
        sympy.Poly(sum(c * t ** i for i, c in enumerate(delta)), t).is_irreducible)
    labs = ['K_0 (= 6_3)', 'K_1', 'K_2']
    out['LT_signatures_all_agree'] = all(
        out['levine_tristram'][labs[0]] == out['levine_tristram'][l]
        for l in labs)
    out['LT_all_zero'] = all(x == 0 for l in labs
                             for x in out['levine_tristram'][l])
    out['control_3_1_fires'] = any(x != 0
                                   for x in out['levine_tristram']['control 3_1'])
    out['alexander_K0_equals_K1'] = (out['alexander'].get('K_0 (= 6_3)')
                                     == out['alexander'].get('K_1'))
    out['interpretation'] = (
        'The lemma predicts equality of every Seifert-form invariant. The '
        'signatures agree and all vanish; the trefoil control is nonzero, so '
        'the computation is live. Agreement here is a consistency check, not '
        'new evidence: the lemma already forces it. What is new is the reason, '
        'which converts a list of vanishing computations into an exclusion.')
    with open(out_path, 'w') as fh:
        json.dump(out, fh, indent=1, sort_keys=True)
    for k in ('LT_signatures_all_agree', 'LT_all_zero', 'control_3_1_fires',
              'alexander_K0_equals_K1', 'delta_irreducible_over_Q',
              'delta_K0', 'delta_K1'):
        print(k, '=', out[k])


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1
         else 'results/opus_2026_09_17/zero_surgery_algebraic_concordance.json')
